// ─────────────────────────────────────────────────────────────────────────────
// firebase_options.dart
// Generated by FlutterFire CLI — matched to your existing google-services.json
// Firebase Project: medicinnect (project_id: medicinnect)
// ─────────────────────────────────────────────────────────────────────────────
//
// ℹ️  This file was hand-crafted to match your existing google-services.json.
//    If you run `flutterfire configure` it will auto-regenerate this properly.
//
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'reconfigure by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'reconfigure by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Values extracted from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JQRqMgTaBihsyILo70FNhTyVPiAru4I',
    appId: '1:27363179803:android:fef0214d05eed5be36a7be',
    messagingSenderId: '27363179803',
    projectId: 'medicinnect',
    storageBucket: 'medicinnect.firebasestorage.app',
  );
}
